# Generated by Django 5.2.4 on 2025-09-10 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='pending_claim_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_claim_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='businesses__status_94f785_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_premium'], name='businesses__is_prem_962b00_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['average_rating'], name='businesses__average_3219b9_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='businesses__slug_9e86f6_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['claimed_by'], name='businesses__claimed_5b0645_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['pending_claim_by'], name='businesses__pending_0472b0_idx'),
        ),
    ]
