# Generated by Django 5.2.4 on 2025-10-02 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
        ('categories', '0002_category_categories__busines_c91f86_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status', 'average_rating'], name='biz_status_avg'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_premium', 'average_rating'], name='biz_premium_avg'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__gte', 0.0), ('average_rating__lte', 5.0)), name='biz_avg_rating_0_5'),
        ),
    ]
