# Generated by Django 5.2.4 on 2025-10-15 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_biz_status_avg_business_biz_premium_avg_and_more'),
        ('categories', '0002_category_categories__busines_c91f86_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('insurances', models.TextField(blank=True, null=True)),
                ('popular_visit_reasons', models.TextField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('zip', models.CharField(blank=True, max_length=32, null=True)),
                ('practice_names', models.TextField(blank=True, null=True)),
                ('educations', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('npi_number', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('pending_claim_notes', models.TextField(blank=True, null=True)),
                ('pending_claim_requested_at', models.DateTimeField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expires', models.DateField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='business',
            old_name='tags',
            new_name='associations',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='business',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='honors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='practice_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='speaking_engagements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='zip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city'], name='businesses__city_0894c6_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['state'], name='businesses__state_bee1bc_idx'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='categories.category'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pending_claim_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_claim_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['status'], name='businesses__status_acf3be_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_premium'], name='businesses__is_prem_7aaf21_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['average_rating'], name='businesses__average_3e5b48_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['slug'], name='businesses__slug_81d679_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['claimed_by'], name='businesses__claimed_97f4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['pending_claim_by'], name='businesses__pending_519386_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['city'], name='businesses__city_1cc306_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['state'], name='businesses__state_606bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['status', 'average_rating'], name='doc_status_avg'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_premium', 'average_rating'], name='doc_premium_avg'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__gte', 0.0), ('average_rating__lte', 5.0)), name='doc_avg_rating_0_5'),
        ),
    ]
