# Generated by Django 5.2.7 on 2025-10-21 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_doctor_rename_tags_business_associations_and_more'),
        ('categories', '0002_category_categories__busines_c91f86_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ('-updated_at', 'id')},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('-updated_at', 'id')},
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['-updated_at'], name='businesses__updated_f642a2_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['-updated_at'], name='businesses__updated_59115c_idx'),
        ),
    ]
