# Generated by Django 5.2.7 on 2025-10-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_business_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='works_for',
            field=models.ForeignKey(blank=True, help_text='Optional link to another business this entity works with/for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliates', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='works_for',
            field=models.ForeignKey(blank=True, help_text='Optional link to the business/clinic this doctor works with/for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='businesses.business'),
        ),
    ]
