# Generated by Django 5.2.7 on 2025-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_business_email_business_works_for_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='works_for',
            field=models.URLField(blank=True, help_text='Optional external website this business works with/for.', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_for',
            field=models.URLField(blank=True, help_text='Optional external website this provider works with/for.', null=True),
        ),
    ]
