# Generated by Django 5.2.4 on 2025-09-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('business_count', models.IntegerField(default=0)),
                ('full_slug', models.CharField(db_index=True, editable=False, max_length=1024, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
            ],
            options={
                'ordering': ['full_slug'],
                'indexes': [models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'), models.Index(fields=['full_slug'], name='categories__full_sl_4a099f_idx'), models.Index(fields=['parent'], name='categories__parent__91c7d9_idx')],
                'unique_together': {('parent', 'slug')},
            },
        ),
    ]
