# Generated by Django 5.2.4 on 2025-09-11 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdfundCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('goal_cents', models.PositiveIntegerField(default=12000)),
                ('amount_raised_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('funded', 'Funded'), ('closed', 'Closed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crowdfund', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('requires_payment', 'Requires Payment'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='requires_payment', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='crowdfund.crowdfundcampaign')),
            ],
        ),
        migrations.AddIndex(
            model_name='crowdfundcampaign',
            index=models.Index(fields=['status'], name='crowdfund_c_status_583094_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdfundcampaign',
            index=models.Index(fields=['business'], name='crowdfund_c_busines_e736eb_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['campaign'], name='crowdfund_c_campaig_9563fd_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['status'], name='crowdfund_c_status_958e01_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['stripe_checkout_session_id'], name='crowdfund_c_stripe__15b47b_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['stripe_payment_intent_id'], name='crowdfund_c_stripe__231d8f_idx'),
        ),
    ]
