# Generated by Django 5.2.4 on 2025-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfundcampaign',
            name='goal_cents',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
