# Generated by Django 5.2.4 on 2025-10-15 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_doctor_rename_tags_business_associations_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crowdfund', '0002_alter_crowdfundcampaign_goal_cents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='contribution',
            name='crowdfund_c_campaig_9563fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='crowdfundcampaign',
            name='crowdfund_c_status_583094_idx',
        ),
        migrations.RemoveIndex(
            model_name='crowdfundcampaign',
            name='crowdfund_c_busines_e736eb_idx',
        ),
        migrations.AddField(
            model_name='crowdfundcampaign',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='crowdfundcampaign',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('requires_payment', 'Requires payment'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='requires_payment', max_length=32),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crowdfundcampaign',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Legacy link; generic target below is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crowdfund_campaigns', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='crowdfundcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crowdfundcampaign',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AlterField(
            model_name='crowdfundcampaign',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['created_at'], name='crowdfund_c_created_692d12_idx'),
        ),
        migrations.AddConstraint(
            model_name='crowdfundcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', False)), fields=('business',), name='uniq_crowdfundcampaign_business_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='crowdfundcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('content_type', 'object_id'), name='uniq_crowdfundcampaign_target_nonnull'),
        ),
    ]
