# Generated by Django 5.2.4 on 2025-09-10 09:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_reply', models.TextField(blank=True, null=True)),
                ('owner_replied_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business')),
            ],
        ),
    ]
