# Generated by Django 5.2.4 on 2025-09-10 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=64)),
                ('meta_type', models.CharField(choices=[('static', 'Static'), ('business', 'Business')], default='static', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.URLField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots', models.CharField(default='index, follow', max_length=50)),
                ('priority', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_meta', to='businesses.business')),
            ],
            options={
                'indexes': [models.Index(fields=['page_name'], name='seo_pagemet_page_na_aa0262_idx'), models.Index(fields=['meta_type'], name='seo_pagemet_meta_ty_06cd74_idx'), models.Index(fields=['is_active'], name='seo_pagemet_is_acti_741f05_idx'), models.Index(fields=['-updated_at'], name='seo_pagemet_updated_f36573_idx')],
                'unique_together': {('page_name', 'meta_type', 'business')},
            },
        ),
    ]
