# Generated by Django 5.2.4 on 2025-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_doctor_rename_tags_business_associations_and_more'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemeta',
            name='auto_managed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='pagemeta',
            index=models.Index(fields=['business'], name='seo_pagemet_busines_e5500d_idx'),
        ),
    ]
