# Generated by Django 5.2.7 on 2025-10-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_business_options_alter_doctor_options_and_more'),
        ('seo', '0002_pagemeta_auto_managed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemeta',
            options={'ordering': ('-updated_at', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='pagemeta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_meta', to='businesses.doctor'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='meta_type',
            field=models.CharField(choices=[('static', 'Static'), ('business', 'Business'), ('doctor', 'Doctor')], default='static', max_length=10),
        ),
        migrations.AddIndex(
            model_name='pagemeta',
            index=models.Index(fields=['doctor'], name='seo_pagemet_doctor__18c397_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemeta',
            index=models.Index(condition=models.Q(('meta_type', 'static')), fields=['page_name'], name='pm_static_pagename_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemeta',
            index=models.Index(condition=models.Q(('meta_type', 'business')), fields=['business'], name='pm_business_id_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemeta',
            index=models.Index(condition=models.Q(('meta_type', 'doctor')), fields=['doctor'], name='pm_doctor_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagemeta',
            constraint=models.UniqueConstraint(condition=models.Q(('meta_type', 'static')), fields=('page_name',), name='uniq_static_page_name'),
        ),
        migrations.AddConstraint(
            model_name='pagemeta',
            constraint=models.UniqueConstraint(condition=models.Q(('meta_type', 'business')), fields=('page_name', 'business'), name='uniq_business_page_meta'),
        ),
        migrations.AddConstraint(
            model_name='pagemeta',
            constraint=models.UniqueConstraint(condition=models.Q(('meta_type', 'doctor')), fields=('page_name', 'doctor'), name='uniq_doctor_page_meta'),
        ),
    ]
